<?php

/**
 * Implements hook_menu
 */
function htaccess_checker_menu() {
  $items = array();
  $items['admin/config/search/htaccess_check'] = array(
    'title' => t('Htaccess Checker'),
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('htaccess_checker_admin'),
  );
  return $items;
}

function htaccess_checker_form_htaccess_checker_admin_alter(&$form, &$form_state, $form_id) {
  $form['#after_build'][] = 'htaccess_checker_theme_form';
}

function htaccess_checker_theme_form(&$form, &$form_state) {
  drupal_add_css(drupal_get_path('module','htaccess_checker') . '/css/htaccess_checker-form.css');
  drupal_add_css(drupal_get_path('module','htaccess_checker') . '/datatables/datatables.min.css');
  drupal_add_js(drupal_get_path('module','htaccess_checker') . '/datatables/datatables.min.js');
  drupal_add_js(drupal_get_path('module','htaccess_checker') . '/js/table.js', array('scope' => 'footer'));
  return $form;
}

function htaccess_checker_get_redirects() {
  $redirects = null;
  return $redirects;
}

function htaccess_checker_initialize_table() {
  $header = array(
    'Source',
    'Target',
    'Pass/Fail',
  );

  // Retrieve saved redirects
  $redirects = htaccess_checker_get_redirects();

  // Initialize the array that contains the data
  $options = array();

  if (!$redirects) {
    $options[$redirects[0]] = array(
      'source' => '',
      'target' => '',
      'result' => ''
    );
  }

  $variables = array(
    'header' => $header,
    'rows' => $options,
  );

  theme_table($variables);

}

function htaccess_checker_new_row($i) {
  return '<tr>
    <td><input type="text" id="row-' . $i . '-src" name="row-' . $i . '-src"></td>
    <td><input type="text" id="row-' . $i . '-tgt" name="row-' . $i . '-tgt"></td>
    <td></td>
    </tr>';
}

function htaccess_checker_return_table() {
  $i = 0;
  $rows = htaccess_checker_new_row($i);
  return '
    <table id="redirects" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Source</th>
                <th>Target</th>
                <th>Pass/Fail</th>
            </tr>
        </thead>
        <tbody>
            ' . $rows . '
        </tbody>
    </table>
  ';
}

/**
 * Settings variables
 */
function htaccess_checker_admin() {
  $form = array();

  $form['htaccess_csv_upload'] = array(
    '#type' => 'file',
  );

  $form['#prefix'] = '<div id="htaccess-check">';
  $form['#suffix'] = '</div>';

  $table = htaccess_checker_return_table();
  //$table = htaccess_checker_initialize_table();

  $form['redirects'] = array(
    '#markup' => $table,
  );

  $form['add_row'] = array(
    '#markup' => '<input type="submit" id="add-row" class="form-submit" value="Add Row">',
  );

  /*$form['redirects']['source'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' => '',
    '#size' => 60,
    '#maxlength' => 128,
  );

  $form['redirects']['target'] = array(
    '#type' => 'textfield',
    '#title' => t('Target'),
    '#default_value' => '',
    '#size' => 60,
    '#maxlength' => 128,
  );*/

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
    '#ajax' => array(
      'callback' => 'htaccess_checker_callback',
      'event' => 'click',
      'wrapper' => 'htaccess-check',
      'method' => 'after',
      'effect' => 'fade',
    ),
  );

  $form['results'] = array();

  //return system_settings_form($form);
  return $form;
}

/**
 * Callback for htaccess checker form
 *
 * @param $form
 * @param $form_state
 */
function htaccess_checker_callback(&$form, $form_state) {

  if ($errors = form_get_errors()) {
    return $form;
  }

  // setup redirects list
  $redirects = array();
  $redirect_count = 0;

  // setup ajax commands array
  $commands = array();

  // save file to temp dir
  $file = file_save_upload('htaccess_csv_upload', array('file_validate_extensions' => array('csv')), "temporary://", $replace = FILE_EXISTS_REPLACE);
  if ($file) {
    $row = 0;
    // deal with mac line endings (from http://php.net/manual/en/function.fgetcsv.php#87196)
    ini_set('auto_detect_line_endings',TRUE);
    if (($handle = fopen($file->uri, "r")) !== FALSE) {
      while (($data = fgetcsv($handle, 500, ",")) !== FALSE) {
        $redirects[$row]['src'] = $data[0];
        $redirects[$row]['tgt'] = $data[1];
        $row++;
        $redirect_count++;
      }
      fclose($handle);
    }
    ini_set('auto_detect_line_endings',FALSE);

    //$num_redirects = count($redirects);
    $successful_redirects = 0;
    $no_redirects = array();
    $wrong_redirects = array();

    foreach ($redirects as $i => $redirect) {
      $src = $redirect['src'];
      $tgt = $redirect['tgt'];
      // set up headers
      $headers = array(
        'Host: ' . $src
      );
      //header("Host: " . $src);
      // curl
      $curl = curl_init();
      curl_setopt($curl,CURLOPT_HTTPHEADER,$headers);
      curl_setopt($curl,CURLOPT_URL,$tgt);
      //curl_setopt($curl,CURLOPT_HEADER,true);
      curl_setopt($curl,CURLINFO_HEADER_OUT,true);
      curl_setopt($curl,CURLOPT_RETURNTRANSFER,true);
      $result = curl_exec($curl);
      $curl_header_sent = curl_getinfo($curl,CURLINFO_HEADER_OUT);
      $curl_effective_url = curl_getinfo($curl,CURLINFO_EFFECTIVE_URL);

      // The effective url will have a trailing slash.
      // Make sure the target also gets the slash for a valid comparison

      if (substr($tgt, -1) !== '/') {
        $tgt = $tgt . '/';
      }

      if (substr($curl_effective_url, -1) !== '/') {
        $curl_effective_url = $curl_effective_url . '/';
      }

      // String comparison
      if ($tgt == $curl_effective_url) {
        $successful_redirects++;
      }
      elseif ($src == $curl_effective_url) {
        $no_redirects[$i]['src'] = $src;
        $no_redirects[$i]['tgt'] = $tgt;
        $no_redirects[$i]['effective'] = $curl_effective_url;
      }
      else {
        $wrong_redirects[$i]['src'] = $src;
        $wrong_redirects[$i]['tgt'] = $tgt;
        $wrong_redirects[$i]['effective'] = $curl_effective_url;
      }
    }
    curl_close($curl);

    // Redirect count
    $commands[] = ajax_command_append('#htaccess-check', $redirect_count . ' redirects found in file ' . $file->filename);

    // Format response
    $successful_report = '<div class="success-redirects"><span class="success">' . $successful_redirects . '</span> redirects tested successfully.</div>';
    $commands[] = ajax_command_append('#htaccess-check', $successful_report);

    // No redirects report
    if (!empty($no_redirects)) {
      $no_redirect_report = array();
      foreach ($no_redirects as $i => $no_redirect) {
        $no_redirect_report[] = '<div class="no-redirects"><span class="src">' . $no_redirect['src'] . '</span> failed to redirect to <span class="tgt">' . $no_redirect['tgt'] . '</span> and instead redirected to <span class="effective">' . $no_redirect['effective'] . '</span></div>';
      }
      $commands[] = ajax_command_append('#htaccess-check', implode('',$no_redirect_report));
    }

    // Wrong redirects report
    if (!empty($wrong_redirects)) {
      $wrong_redirect_report = array();
      foreach ($wrong_redirects as $i => $wrong_redirect) {
        $wrong_redirect_report[] = '<div class="wrong-redirects"><span class="src">' . $wrong_redirect['src'] . '</span> failed to redirect to <span class="tgt">' . $wrong_redirect['tgt'] . '</span> and instead redirected to <span class="effective">' . $wrong_redirect['effective'] . '</span></div>';
      }
      $commands[] = ajax_command_append('#htaccess-check', implode('',$wrong_redirect_report));
    }

    return array(
      '#type' => 'ajax',
      '#commands' => $commands,
    );
  }
  else {
    $commands[] = ajax_command_append('#htaccess-check', 'No file uploaded.');
  }
}
